version = 0.1

[core.build.parameters]
template_file = "template.yaml"
manifest = "package.json"

[dev.deploy.parameters] 
profile = "default"
region = "us-east-2"
stack_name = "HSP-Submissions-Dev"
capabilities = "CAPABILITY_NAMED_IAM"
s3_bucket = "hsp-dev-deployments"
s3_prefix = "hsp-submissions-dev"
parameter_overrides = [
    "DeployEnv=DEV",
]

[prod.deploy.parameters] 
profile = "default"
region = "us-east-2"
stack_name = "HSP-Submissions-Prod"
capabilities = "CAPABILITY_NAMED_IAM"
s3_bucket = "hsp-prod-deployments"
s3_prefix = "hsp-submissions-prod"
parameter_overrides = [
    "DeployEnv=PROD",
]
