// File mapping of sections > tab > file to display
export const fileMapping = {
  "Volcano Plot": {
    Visualization: "volcano_0_dpi150.png",
    "Data Matrix": "volcano.csv",
  },
  Heatmap: {
    "Top Samples": "heatmap_1_dpi150.png",
    "All Samples": "heatmap_0_dpi150.png",
  },
  "Statistical Parametric Test": {
    Visualization: "tt_0_dpi150.png",
    "Data Matrix": "statistical_parametric_test.csv",
  },
  "Fold Change Analysis": {
    Visualization: "fc_0_dpi150.png",
    "Data Matrix": "fold_change.csv",
  },
  "Principal Component Analysis": {
    Visualization: "pca_score2d_0_dpi150.png",
    "Data Matrix": "pca_score.csv",
    "PCA Score": "pca_score.csv",
    "Group Labels": "data_normalized.csv",
    "PCA Variance": "pca_variance.csv",
  },
  "Venn-Diagram": {
    Visualization: "venn-dimensions.png",
    "Data Matrix": "venn_out_data.txt",
  },
  Normalization: {
    Visualization: "norm_0_dpi150.png",
    "Data Original": "data_original.csv",
    "Data Normalized": "data_normalized.csv",
  },
  "Input Data": "data_original.csv",
  "Result Data": "all_data.tsv",
  "Random Forest": {
    Classification: ["rf_cls_0_dpi150.png", "randomforest_confusion.csv"],
    Feature: ["rf_imp_0_dpi150.png", "randomforests_sigfeatures.csv"],
    Outlier: ["rf_outlier_0_dpi150.png"],
  },
  "GO Biological Process": {
    "Enrichment Plot": "gobp_bar.jpeg",
    "Enrichment Plot Data": "egobp.tsv",
    "Enriched terms & connected genes": "gobp_gene_network.jpeg",
    "GSEA Ridge plot": "gsebp_ridge.jpeg",
    "GSEA Heatmap plot": "gsebp_heat.jpeg",
    "GSEA Tree cluster plot": "gobp_tree.jpeg",
  },
  "GO Molecular Function": {
    "Enrichment Plot": "gomf_bar.jpeg",
    "Enrichment Plot Data": "egomf.tsv",
    "Enriched terms & connected genes": "gomf_gene_network.jpeg",
    "GSEA Ridge plot": "gsemf_ridge.jpeg",
    "GSEA Heatmap plot": "gsemf_heat.jpeg",
    "GSEA Tree cluster plot": "gomf_tree.jpeg",
  },
  "GO Cellular Component": {
    "Enrichment Plot": "gocc_bar.jpeg",
    "Enrichment Plot Data": "egocc.tsv",
    "Enriched terms & connected genes": "gocc_gene_network.jpeg",
    "GSEA Ridge plot": "gsecc_ridge.jpeg",
    "GSEA Heatmap plot": "gsecc_heat.jpeg",
    "GSEA Tree cluster plot": "gocc_tree.jpeg",
  },
  "KEGG Pathway/Module": {
    "Enrichment Plot": "kegg_pathway_bar.jpeg",
    "Enrichment Plot Data": "kegg.tsv",
    "Enriched terms & connected genes": "kegg_gene_network.jpeg",
    "GSEA Ridge plot": "kegg_pathway_ridge.jpeg",
    "GSEA Heatmap plot": "kegg_heat.jpeg",
    "GSEA Tree cluster plot": "kegg_tree.jpeg",
  },
};

// Mapping of tabs for each section of results page
export const sectionToTabs = {
  Heatmap: [`Top <-numbOfTopVolcanoSamples-> Samples`, "All Samples"],
  "Random Forest": ["Classification", "Feature", "Outlier"],
  "Volcano Plot": ["Visualization", "Data Matrix"],
  "Statistical Parametric Test": ["Visualization", "Data Matrix"],
  "Fold Change Analysis": ["Visualization", "Data Matrix"],
  "Principal Component Analysis": ["Visualization", "Data Matrix"],
  "Venn-Diagram": ["Visualization", "Data Matrix"],
  Normalization: ["Visualization", "Data Matrix"],
  "GO Biological Process": [
    "Enrichment Plot",
    "Enriched terms & connected genes",
    "GSEA Ridge plot",
    "GSEA Heatmap plot",
    "GSEA Tree cluster plot",
  ],
  "GO Molecular Function": [
    "Enrichment Plot",
    "Enriched terms & connected genes",
    "GSEA Ridge plot",
    "GSEA Heatmap plot",
    "GSEA Tree cluster plot",
  ],
  "GO Cellular Component": [
    "Enrichment Plot",
    "Enriched terms & connected genes",
    "GSEA Ridge plot",
    "GSEA Heatmap plot",
    "GSEA Tree cluster plot",
  ],
  "KEGG Pathway/Module": [
    "Enrichment Plot",
    "Enriched terms & connected genes",
    "GSEA Ridge plot",
    "GSEA Heatmap plot",
    "GSEA Tree cluster plot",
  ],
};

// Mapping of each download link to file name in s3
export const downloadMapping = {
  "Volcano Plot": "volcano_0_dpi150.png",
  "Volcano Data": "volcano.csv",
  "Top 25 Samples Heatmap": "heatmap_1_dpi150.png",
  "All Samples Heatmap": "heatmap_0_dpi150.png",
  "Statistical Parametric Test Plot": "tt_0_dpi150.png",
  "Statistical Parametric Test Data": "statistical_parametric_test.csv",
  "Fold Change Analysis Plot": "fc_0_dpi150.png",
  "Fold Change Analysis Data": "fold_change.csv",
  "Principal Component Analysis Plot": "pca_score2d_0_dpi150.png",
  "Principal Component Analysis Data": "pca_score.csv",
  "Venn-Diagram Plot": "venn-dimensions.png",
  "Venn-Diagram Data": "venn_out_data.txt",
  "Normalization Plot": "norm_0_dpi150.png",
  "Normalization Data": "data_normalized.csv",
  "Input Data": "data_original.csv",
  "Random Forest CLS": "rf_cls_0_dpi150.png",
  "Random Forest IMP": "rf_imp_0_dpi150.png",
  "Random Forest Outlier": "rf_outlier_0_dpi150.png",
  // "GO Biological Process": "",
  // "GO Molecular Function": "",
  // "GO Cellular Component": "",
  // "KEGG Pathway/Module": "",
  "Result Data": "all_data.tsv",
  "All Data Set": "data_set.zip",
};

export const option = [
  "Volcano Plot",
  "Heatmap",
  "Statistical Parametric Test",
  "Fold Change Analysis",
  "Principal Component Analysis",
  "Venn-Diagram",
  "Normalization",
  "Random Forest",
  "GO Biological Process",
  "GO Molecular Function",
  "GO Cellular Component",
  "KEGG Pathway/Module",
  "Input Data",
  "Result Data",
  "Download",
];
