AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Differential Analysis Advanced Lambda. GO/KEGG Analysis

Parameters:
  DeployEnv:
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - PROD
  ApiStage:
    Type: String
    Description: The APIGateway stage name.
    Default: v1
  S3BucketName:
    Type: String
  SupportEmail:
    Type: String

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: "Differential-Analysis-Advance"
      StageName: !Ref ApiStage
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  ApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      DockerContext: .
      Dockerfile: Dockerfile
    Properties:
      PackageType: Image
      FunctionName: "Differential-Analysis-Advance"
      Description: Differential Analysis Advance
      Role: arn:aws:iam::552623730819:role/HSP-Api-Execution-Role
      MemorySize: 2048
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          SUPPORT_EMAIL: !Ref SupportEmail
      Timeout: 900
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+} # direct pass through of any route after /
            Method: ANY
