AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: HSP Api

Parameters:
  DeployEnv:
    Type: String
    Default: DEV
    AllowedValues:
      - DEV
      - STAG
      - PROD
  ApiStage:
    Type: String
    Description: The APIGateway stage name.
    Default: v1
  SmtpUser:
    Type: String
  SmtpPassword:
    Type: String
  RecaptchaSecretKey:
    Type: String
  DifferentialS3Bucket:
    Type: String
  RScriptPath:
    Type: String
  RScriptFileName:
    Type: String
  ContactTable:
    Type: String
  ContactS3Bucket:
    Type: String
  IndexProteinCluster:
    Type: String
  IndexSalivaryProtein:
    Type: String
  IndexGene:
    Type: String
  IndexProteinSignature:
    Type: String
  IndexCitation:
    Type: String
  IndexSalivarySummary:
    Type: String
  IndexGoNodes:
    Type: String
  IndexGoEdges:
    Type: String
  IndexStudy:
    Type: String
  IndexStudyProtein:
    Type: String
  IndexPeptide:
    Type: String
  IndexStudyPeptideAbundance:
    Type: String
  OsHostname:
    Type: String

Resources:
  HSPApiLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HSP-Api-Execution-Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - lambda.amazonaws.com
                - !Sub states.${AWS::Region}.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: HSP-Api-Execution-Role-Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: LogsAccess
                Effect: "Allow"
                Action:
                  - "logs:DescribeLogGroups"
                  - "logs:DescribeLogStreams"
                  - "logs:GetLogEvents"
                  - "logs:FilterLogEvents"
                Resource: "*"
              - Sid: ParameterStore
                Effect: "Allow"
                Action:
                  - "ssm:GetParametersByPath"
                  - "ssm:GetParameter"
                  - "ssm:GetParameters"
                  - "ssm:DescribeParameters"
                  - "ssm:PutParameter"
                Resource: "*"
              - Sid: S3Access
                Effect: "Allow"
                Action:
                  - "s3:PutObjectTagging"
                  - "s3:PutObjectAcl"
                  - "s3:PutObject"
                  - "s3:ListMultipartUploadParts"
                  - "s3:ListBucketMultipartUploads"
                  - "s3:ListBucket"
                  - "s3:GetObjectVersion"
                  - "s3:GetObjectAcl"
                  - "s3:GetObject"
                  - "s3:GetEncryptionConfiguration"
                  - "s3:GetBucketWebsite"
                  - "s3:GetBucketPolicy"
                  - "s3:GetBucketLocation"
                  - "s3:GetBucketCORS"
                  - "s3:GetBucketAcl"
                  - "s3:DeleteObject"
                  - "s3:AbortMultipartUpload"
                Resource: "*"
              - Sid: DynamoDB
                Effect: "Allow"
                Action:
                  - "dynamodb:DeleteItem"
                  - "dynamodb:DescribeTable"
                  - "dynamodb:GetItem"
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:BatchWriteItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:CreateTable"
                Resource: "*"

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: "HSP-Api"
      StageName: !Ref ApiStage
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  # create permission for API Gateway to execute Lambda function
  ApiGatewayExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ApiFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ""
        - - "arn:aws:execute-api:"
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - ":"
          - !Ref ApiGateway
          - "/*/*"

  ApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      DockerTag: nodejs16.x-v1
      DockerContext: .
      Dockerfile: Dockerfile
    Properties:
      PackageType: Image
      FunctionName: "HSP-Api"
      Description: HSP Api
      Role: !GetAtt HSPApiLambdaRole.Arn
      # CodeUri: api/
      # Handler: lambda.handler
      # Runtime: nodejs16.x
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          DEPLOY_ENV: !Ref DeployEnv
          SMTP_USER: !Ref SmtpUser
          SMTP_PASSWORD: !Ref SmtpPassword
          RECAPTCHA_SECRET_KEY: !Ref RecaptchaSecretKey
          DIFFERENTIAL_S3_BUCKET: !Ref DifferentialS3Bucket
          R_SCRIPT_PATH: !Ref RScriptPath
          R_SCRIPT_FILE_NAME: !Ref RScriptFileName
          CONTACT_TABLE: !Ref ContactTable
          CONTACT_S3_BUCKET: !Ref ContactS3Bucket
          INDEX_PROTEIN_CLUSTER: !Ref IndexProteinCluster
          INDEX_SALIVARY_PROTEIN: !Ref IndexSalivaryProtein
          INDEX_GENE: !Ref IndexGene
          INDEX_PROTEIN_SIGNATURE: !Ref IndexProteinSignature
          INDEX_CITATION: !Ref IndexCitation
          INDEX_SALIVARY_SUMMARY: !Ref IndexSalivarySummary
          INDEX_GO_NODES: !Ref IndexGoNodes
          INDEX_GO_EDGES: !Ref IndexGoEdges
          INDEX_STUDY: !Ref IndexStudy
          INDEX_STUDY_PROTEIN: !Ref IndexStudyProtein
          INDEX_PEPTIDE: !Ref IndexPeptide
          INDEX_STUDY_PEPTIDE_ABUNDANCE: !Ref IndexStudyPeptideAbundance
          OS_HOSTNAME: !Ref OsHostname
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY
        ProxyApiGreedy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+} # direct pass through of any route after /
            Method: ANY
